### ISSUE TITLE
test breaks

### ISSUE THREAD

**Issue by JiffB** [inaka/erlang-katana#153]
Debian stable (stretch)
Erlang Solution pkgs 20.1-1

Hi folks,

2 tests are failing, the 1st one because of gen_fsm use instead of gen_statem,
and the 2nd one because it can't access 'w4th3v3r' :

$ rebar3 ct
===> Verifying dependencies...
===> Compiling katana
===> Running Common Test suites...
%%% ktn_base16_SUITE ==> encode: OK
%%% ktn_binary_SUITE ==> join: OK
%%% ktn_fsm_SUITE ==> secure_vault: OK
%%% ktn_lists_SUITE ==> delete_first: OK
%%% ktn_lists_SUITE ==> split_when: OK
%%% ktn_lists_SUITE ==> map: OK
%%% ktn_lists_SUITE ==> filter: OK
%%% ktn_maps_SUITE ==> find_nested_values: OK
%%% ktn_maps_SUITE ==> find_shallow_values: OK
%%% ktn_maps_SUITE ==> dont_find_nested_values: OK
%%% ktn_maps_SUITE ==> dont_find_shallow_values: OK
%%% ktn_maps_SUITE ==> provide_default: OK
%%% ktn_meta_SUITE ==> dialyzer: OK
%%% ktn_meta_SUITE ==> elvis: OK
%%% ktn_meta_SUITE ==> xref: FAILED
%%% ktn_meta_SUITE ==> {{badmatch,[#{check => deprecated_function_calls,
              filename =>
                  "/usr/local/lib/erlang/lib/erlang-katana/_build/test/lib/katana/src/ktn_fsm.erl",
              line => 34,
              source => {ktn_fsm,call,2},
              target => {gen_fsm,sync_send_event,2}},
            #{check => deprecated_function_calls,
              filename =>
                  "/usr/local/lib/erlang/lib/erlang-katana/_build/test/lib/katana/src/ktn_fsm.erl",
              line => 38,
              source => {ktn_fsm,call,3},
              target => {gen_fsm,sync_send_event,3}},
            #{check => deprecated_function_calls,
              filename =>
                  "/usr/local/lib/erlang/lib/erlang-katana/_build/test/lib/katana/src/ktn_fsm.erl",
              line => 42,
              source => {ktn_fsm,call_through,2},
              target => {gen_fsm,sync_send_all_state_event,2}},
            #{check => deprecated_function_calls,
              filename =>
                  "/usr/local/lib/erlang/lib/erlang-katana/_build/test/lib/katana/src/ktn_fsm.erl",
              line => 46,
              source => {ktn_fsm,call_through,3},
              target => {gen_fsm,sync_send_all_state_event,3}},
            #{check => deprecated_function_calls,
              filename =>
                  "/usr/local/lib/erlang/lib/erlang-katana/_build/test/lib/katana/src/ktn_fsm.erl",
              line => 50,
              source => {ktn_fsm,cast,2},
              target => {gen_fsm,send_event,2}},
            #{check => deprecated_function_calls,
              filename =>
                  "/usr/local/lib/erlang/lib/erlang-katana/_build/test/lib/katana/src/ktn_fsm.erl",
              line => 54,
              source => {ktn_fsm,cast_through,2},
              target => {gen_fsm,send_all_state_event,2}}]},
 [{ktn_meta_SUITE,xref,1,
                  [{file,"/usr/local/lib/erlang/lib/erlang-katana/_build/test/lib/katana/test/ktn_meta_SUITE.erl"},
                   {line,46}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1539}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1055}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,987}]}]}
%%% ktn_numbers_SUITE ==> bin_to_number: OK
%%% ktn_os_SUITE ==> command: FAILED
%%% ktn_os_SUITE ==> {{badmatch,{2,
            "/usr/local/lib/erlang/lib/erlang-katana/_build/test/logs/ct_run.nonode@nohost.2017-10-16_21.33.30\nls: cannot access 'w4th3v3r': No such file or directory\n"}},
 [{ktn_os_SUITE,command,1,
                [{file,"/usr/local/lib/erlang/lib/erlang-katana/_build/test/lib/katana/test/ktn_os_SUITE.erl"},
                 {line,41}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1539}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1055}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,987}]}]}
%%% ktn_random_SUITE ==> string: OK
%%% ktn_random_SUITE ==> uniform: OK
%%% ktn_random_SUITE ==> pick: OK
%%% ktn_recipe_SUITE ==> implicit_test: OK
%%% ktn_recipe_SUITE ==> explicit_test: OK
%%% ktn_recipe_SUITE ==> loop_test: OK
Failed 2 tests. Passed 21 tests. 
Results written to "/usr/local/lib/erlang/lib/erlang-katana/_build/test/logs/index.html".
===> Failures occurred running tests: 2

Jean-Yves

**Comment by elbrujohalcon** [comment]
Fixed on #153
